apiVersion: v1
kind: Service
metadata:
  name: additional-mysql
  labels:
    app.kubernetes.io/part-of: {{ .Values.metadata.applicationName }}
    app.kubernetes.io/name: additional-mysql
    app.kubernetes.io/component: additional-mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      targetPort: mysql
      name: mysql
  selector:
    app.kubernetes.io/part-of: {{ .Values.metadata.applicationName }}
    app.kubernetes.io/name: additional-mysql
    app.kubernetes.io/component: additional-mysql
